use_frameworks!

platform :ios, '9.0'

target 'BQNetworking_Example' do
  pod 'BQNetworking', :path => '../'

  target 'BQNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
